import { NextIntlClientProvider } from "next-intl";
import { getLocale, getMessages } from "next-intl/server";
import "./globals.css";
import ToasterProvider from "@/providers/ToastProvider";

export const metadata = {
  title: "SurveyCraft",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const locale = await getLocale();

  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body>
        <NextIntlClientProvider locale={locale} messages={messages}>
          <ToasterProvider />
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
